<a href="https://colab.research.google.com/github/khangle2002/ailearningandprojects/blob/main/AIO_Day_11_15.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Day 11***

In [ ]:
A = [[1, 2, 3], [4, 5, 6], [7, 8 ,9]]
B = [[2, 4],[1, 3]]

def convolution(matrix_a, matrix_b):
  n_rows = len(matrix_a)-len(matrix_b)
  n_colums = len(matrix_a[0]) - len(matrix_b[0])
  result = []


  if n_rows < 0 or n_colums < 0:
      return result

  for i in range(n_rows + 1):
      row = []
      for j in range(n_colums + 1):
          sum_value = 0
          for k in range(len(matrix_b)):
              for l in range(len(matrix_b[0])):
                sum_value += matrix_a[i + k][j + l] * matrix_b[k][l]
          row.append(sum_value)
      result.append(row)
  return result

result = convolution(A, B)
print(result)

C = [[1, 1, 1], [0, 0 ,0], [1, 1, 1]]

result = convolution(A, C)
print(result)

[[29, 39], [59, 69]]
[[30]]


In [ ]:
A = [[0, 0, 0], [0, 4, 0], [0, 1, 0]]
B = [[1, 1],[1, 1]]

def padded_convolution(matrix_a, matrix_b, padding_size):
    n_rows = len(matrix_a)
    n_cols = len(matrix_a[0])

    padded_rows = n_rows + 2 * padding_size
    padded_cols = n_cols + 2 * padding_size
    padded_matrix = [[0] * padded_cols for _ in range(padded_rows)]

    for i in range(n_rows):
        for j in range(n_cols):
            padded_matrix[i + padding_size][j + padding_size] = matrix_a[i][j]

    conv_rows = len(padded_matrix) - len(matrix_b)
    conv_cols = len(padded_matrix[0]) - len(matrix_b[0])
    result = []

    if conv_rows < 0 or conv_cols < 0:
        return result

    for i in range(conv_rows + 1):
        row = []
        for j in range(conv_cols + 1):
            sum_value = 0
            for k in range(len(matrix_b)):
                for l in range(len(matrix_b[0])):
                    sum_value += padded_matrix[i + k][j + l] * matrix_b[k][l]
            row.append(sum_value)
        result.append(row)

    return result

result = padded_convolution(A, B, 1)
print(result)

C = [[0, 1, 0], [0, 1, 0], [0, 1, 0]]

result = padded_convolution(A, C, 1)
print(result)

[[0, 0, 0, 0], [0, 4, 4, 0], [0, 5, 5, 0], [0, 1, 1, 0]]
[[0, 4, 0], [0, 5, 0], [0, 5, 0]]


In [ ]:
def max_pooling(matrix, pool_size):
    num_rows = len(matrix)
    num_cols = len(matrix[0])

    out_rows = num_rows // pool_size
    out_cols = num_cols // pool_size

    pooled_matrix = [[0] * out_cols for _ in range(out_rows)]

    for row in range(out_rows):
        for col in range(out_cols):
            start_row = row * pool_size
            start_col = col * pool_size
            max_value = 0
            for i in range(pool_size):
                for j in range(pool_size):
                    max_value = max(max_value, matrix[start_row + i][start_col + j])

            pooled_matrix[row][col] = max_value

    return pooled_matrix

def average_pooling(matrix, pool_size):
    num_rows = len(matrix)
    num_cols = len(matrix[0])

    out_rows = num_rows // pool_size
    out_cols = num_cols // pool_size

    pooled_matrix = [[0] * out_cols for _ in range(out_rows)]

    for row in range(out_rows):
        for col in range(out_cols):
            start_row = row * pool_size
            start_col = col * pool_size
            total = 0
            for i in range(pool_size):
                for j in range(pool_size):
                  total += matrix[start_row + i][start_col + j]

            pooled_matrix[row][col] = total / (pool_size * pool_size)
    return pooled_matrix

A = [[0, 0, 0, 4], [0, 4, 0, 2], [0, 1, 0, 2], [0, 3, 0, 2]]
result_max = max_pooling(A, 2)
result_average = average_pooling(A, 2)
print(result_max)
print(result_average)

[[4, 4], [3, 2]]
[[1.0, 1.5], [1.0, 1.0]]


# Day 12

# Day 13

In [ ]:
import numpy as np
A = np.array([[1, 2],[3, 4]])
B = np.array([[5, 6],[7, 8]])

C = A + B
D = A - B
print(C)

print(D)

[[ 6  8]
 [10 12]]
/n
[[-4 -4]
 [-4 -4]]


In [ ]:
C = np.array([[2, -3],[4, -5]])
D = np.array([[1, 4],[-2, 6]])

print(C+D)
print(C-D)

[[3 1]
 [2 1]]
[[  1  -7]
 [  6 -11]]
